name: learning_notifier_asyncnotifier
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  freezed: ^2.5.8
  freezed_annotation: ^2.4.4
  http: ^1.3.0
  riverpod_annotation: ^2.6.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  riverpod_generator: ^2.6.4
  riverpod_lint: ^2.6.4
  custom_lint: ^0.7.2
  freezed_lint: ^0.0.7
  json_serializable: ^6.9.3

analyzer:
  plugins:
    - custom_lint

flutter:
  uses-material-design: true
